---
- name: Test instances
  hosts: localhost
  tasks:
    # Package tests

    - name: Download APM tool
      get_url: # replace with s3|azure blob download, etc
        url: https://github.com/wttech/APM/releases/download/apm-5.5.1/apm-all-5.5.1.zip
        dest: "{{aem_tmp_dir }}/apm-all-5.5.1.zip"

    - name: Deploy APM package
      wttech.aem.pkg:
        command: deploy
        url: "{{aem_tmp_dir }}/apm-all-5.5.1.zip"

    - name: Read APM package
      wttech.aem.pkg:
        command: find
        instance_id: local_author
        file: "{{aem_tmp_dir }}/apm-all-5.5.1.zip"

    # Repository tests

    - name: Read some node
      wttech.aem.repo_node:
        command: read
        instance_id: local_author
        path: /content/cq:tags/experience-fragments
      register: res

    - name: Print node created time
      ansible.builtin.debug:
        msg: "Node '/content/cq:tags/experience-fragments' was created at '{{ res.data.node.properties['jcr:created'] }}'"

    - name: Save some node
      wttech.aem.repo_node:
        command: save
        instance_id: local_author
        path: /content/foo
        props:
          foo: bar3

    - name: Copy some node
      wttech.aem.repo_node:
        command: copy
        instance_id: local_author
        source_path: /content/foo
        target_path: /content/foo-copy

    # OSGi tests

    - name: Read some bundle
      wttech.aem.osgi_bundle:
        command: read
        instance_id: local_author
        symbolic_name: com.day.cq.wcm.cq-wcm-core
      register: res

    - name: Print read bundle ID
      ansible.builtin.debug:
        msg: "Bundle 'com.day.cq.wcm.cq-wcm-core' has ID '{{ res.data.bundle.details.id }}'"

    - name: Read all bundles
      wttech.aem.osgi_bundle:
        command: list
        instance_id: local_author

    - name: Restart some bundle
      wttech.aem.osgi_bundle:
        command: restart
        symbolic_name: org.apache.abdera.client

# TODO only if hmac/master files are provided
#    - name: Setup Crypto Support
#      wttech.aem.crypto:
#        command: setup
