---
aem:

  java:

  instance:

    # Processing mode
    # 'auto'     - for more than 1 local instances - 'serial', otherwise 'parallel'
    # 'parallel' - for working with remote instances
    # 'serial'   - for working with local instances
    processing_mode: auto

    # Defined by single value (only remote)
    config_url: ''

    # Defined strictly with full details (local or remote)
    config:
      local_author:
        http_url: http://localhost:4502
        user: admin
        password: admin
        run_modes: [ local, scene7 ]
      local_publish:
        http_url: http://localhost:4503
        user: admin
        password: admin
        run_modes: [ local, scene7 ]

    # Filters for defined
    filter:
      id: ''
      author: false
      publish: false

    # State checking
    check:
      interval: 5s

    # Managed locally (set up automatically)
    local:
      unpack_dir: '/Users/krystian.panek/Projects/aemc/aem/home/instance'
      quickstart:
        dist_file: '/Users/krystian.panek/Projects/aemc/aem/home/lib/cq-quickstart-6.5.0.jar'
        license_file: '/Users/krystian.panek/Projects/aemc/aem/home/lib/license.properties'


