---
- name: Setup 'aem_single' environment (author, publish & dispatcher)
  hosts: [aem_single]
  strategy: mitogen_linear
  become: true
  roles:
    - name: wttech.aem.instance
      tags: [aem_instance]
