---
- name: Setup 'aem_single' environment (author, publish & dispatcher)
  hosts: [aem_single]
  # strategy: mitogen_linear
  become: yes
  roles:
    - name: aem_instance
      tags: [aem_instance]
