---

- name: Await instance(s)
  wttech.aem.instance:
    command: await
  become: true
  become_user: "{{ aem_system_user }}"

- name: Deploy service pack
  wttech.aem.pkg:
    command: deploy
    file: "{{ aem_lib_dir }}/aem-service-pkg-6.5.*.0.zip"
  become: true
  become_user: "{{ aem_system_user }}"
  when: aem_project_kind == 'classic'

- name: Enable CRX DE
  wttech.aem.osgi_config:
    command: save
    pid: org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet
    props:
      alias: /crx/server
  become: true
  become_user: "{{ aem_system_user }}"

- name: Configure replication agent for publishing content
  wttech.aem.repl_agent:
    command: setup
    instance_id: local_author
    location: author
    name: publish
    props:
      enabled: true
      transportUri: "{{ aem_publish_http_url }}/bin/receive?sling:authRequestLogin=1"
      transportUser: "{{ aem_instance_user }}"
      transportPassword: "{{ aem_instance_password }}"
      userId: "{{ aem_instance_user }}"
  become: true
  become_user: "{{ aem_system_user }}"

- name: Configure replication agent for flushing dispatcher cache
  wttech.aem.repl_agent:
    command: setup
    instance_id: local_publish
    location: publish
    name: flush
    props:
      enabled: true
      transportUri: "{{ aem_dispatcher_http_url }}/dispatcher/invalidate.cache"
      protocolHTTPHeaders:
        - "CQ-Action: {action}"
        - "CQ-Handle: {path}"
        - "CQ-Path: {path}"
        - "Host: publish"
  become: true
  become_user: "{{ aem_system_user }}"
