---

- name: Ensure config file dir
  file:
    path: "{{ aem_home_dir }}/etc"
    state: directory

- name: Template config file
  template:
    src: aem.yml
    dest: "{{ aem_config_file }}"

- name: Read config file
  ansible.builtin.shell: "cat {{ aem_config_file }}"
  no_log: true
  changed_when: false
  register: res

- name: Parse config file
  set_fact:
    aem: "{{ res.stdout | from_yaml }}"

- name: Create instance(s)
  wttech.aem.instance:
    command: create

- name: Start instance(s)
  wttech.aem.instance:
    command: start

- name: Enable CRX DE
  wttech.aem.osgi_config:
    command: save
    pid: org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet
    props:
      alias: /crx/server

- name: Configure replication agent for publishing content
  wttech.aem.repl_agent:
    command: setup
    instance_id: local_author
    location: author
    name: publish
    props:
      enabled: true
      transportUri: "{{ aem.instance.config.local_publish.http_url }}/bin/receive?sling:authRequestLogin=1"
      transportUser: "{{ aem.instance.config.local_publish.user }}"
      transportPassword: "{{ aem.instance.config.local_publish.password }}"
      userId: "{{ aem.instance.config.local_publish.user }}"

- name: Configure replication agent for flushing dispatcher cache
  wttech.aem.repl_agent:
    command: setup
    instance_id: local_publish
    location: publish
    name: flush
    props:
      enabled: true
      transportUri: "{{ aem_dispatcher_http_url }}/dispatcher/invalidate.cache"
      protocolHTTPHeaders:
        - "CQ-Action: {action}"
        - "CQ-Handle: {path}"
        - "CQ-Path: {path}"
        - "Host: publish"
